package csg;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up To Do List Maker workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum CSGPropertyType {

    /* THESE ARE THE NODES IN OUR APP */
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OH_OK_PROMPT,
    OH_CANCEL_PROMPT,

    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S OH WORKSPACE CONTROLS
    OH_LEFT_PANE,
    OH_TAS_HEADER_PANE,
    OH_TAS_HEADER_LABEL,
    OH_GRAD_UNDERGRAD_TAS_PANE,
    OH_ALL_RADIO_BUTTON,
    OH_GRAD_RADIO_BUTTON,
    OH_UNDERGRAD_RADIO_BUTTON,
    OH_TAS_HEADER_TEXT_FIELD,
    OH_TAS_TABLE_VIEW,
    OH_NAME_TABLE_COLUMN,
    OH_EMAIL_TABLE_COLUMN,
    OH_SLOTS_TABLE_COLUMN,
    OH_TYPE_TABLE_COLUMN,

    OH_ADD_TA_PANE,
    OH_NAME_TEXT_FIELD,
    OH_EMAIL_TEXT_FIELD,
    OH_ADD_TA_BUTTON,

    OH_RIGHT_PANE,
    OH_OFFICE_HOURS_HEADER_PANE,
    OH_OFFICE_HOURS_HEADER_LABEL,
    OH_OFFICE_HOURS_TABLE_VIEW,
    OH_START_TIME_TABLE_COLUMN,
    OH_END_TIME_TABLE_COLUMN,
    OH_MONDAY_TABLE_COLUMN,
    OH_TUESDAY_TABLE_COLUMN,
    OH_WEDNESDAY_TABLE_COLUMN,
    OH_THURSDAY_TABLE_COLUMN,
    OH_FRIDAY_TABLE_COLUMN,
    OH_DAYS_OF_WEEK,
    OH_FOOLPROOF_SETTINGS,
    
    // FOR THE EDIT DIALOG
    OH_TA_EDIT_DIALOG,
    OH_TA_DIALOG_GRID_PANE,
    OH_TA_DIALOG_HEADER_LABEL, 
    OH_TA_DIALOG_NAME_LABEL,
    OH_TA_DIALOG_NAME_TEXT_FIELD,
    OH_TA_DIALOG_EMAIL_LABEL,
    OH_TA_DIALOG_EMAIL_TEXT_FIELD,
    OH_TA_DIALOG_TYPE_LABEL,
    OH_TA_DIALOG_TYPE_BOX,
    OH_TA_DIALOG_GRAD_RADIO_BUTTON,
    OH_TA_DIALOG_UNDERGRAD_RADIO_BUTTON,
    OH_TA_DIALOG_OK_BOX,
    OH_TA_DIALOG_OK_BUTTON, 
    OH_TA_DIALOG_CANCEL_BUTTON, 
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    OH_NO_TA_SELECTED_TITLE, OH_NO_TA_SELECTED_CONTENT,
    
    // THESE ARE FOR THE TABS
    SITE_TAB_TEXT,
    SYLLABUS_TAB_TEXT,
    MT_TAB_TEXT,
    OH_TAB_TEXT,
    SCH_TAB_TEXT,
    
    // THESE ARE FOR THE SITE TAB WORKSPACE
    SITE_BANNER_LABEL,
    SITE_FALL_TEXT,
    SITE_SPRING_TEXT,
    SITE_SUMMER_TEXT,
    SITE_WINTER_TEXT,
    SITE_SUBJECT_LABEL,
    SITE_SEMESTER_LABEL,
    SITE_NUMBER_LABEL,
    SITE_YEAR_LABEL,
    SITE_TITLE_LABEL,
    SITE_EXPDIR_LABEL,
    SITE_PAGES_LABEL,
    SITE_HOME_LABEL,
    SITE_SYLLABUS_LABEL,
    SITE_SCHEDULE_LABEL,
    SITE_HWS_LABEL,
    SITE_STYLE_LABEL,
    SITE_FAVICON_BUTTON,
    SITE_NAVBAR_BUTTON,
    SITE_LFIMG_BUTTON,
    SITE_RFIMG_BUTTON,
    SITE_FONTSTYLE_LABEL,
    SITE_FONTSTYLENOTE_LABEL,
    SITE_INSTRUCTOR_LABEL,
    SITE_NAME_LABEL,
    SITE_EMAIL_LABEL,
    SITE_ROOM_LABEL,
    SITE_HP_LABEL,
    SITE_EXPAND_BUTTON,
    SITE_OH_LABEL,
    SITE_CSE_TEXT,
    SITE_101_TEXT,
    SITE_114_TEXT,
    SITE_214_TEXT,
    SITE_215_TEXT,
    SITE_216_TEXT,
    SITE_219_TEXT,
    DEFAULT_IMAGES_PATH_TEXT,
    DEFAULT_FAVICON_TEXT,
    DEFAULT_NAVBAR_TEXT,
    DEFAULT_LFIMG_TEXT,
    DEFAULT_RFIMG_TEXT,

    
}